apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "groundschool.fullname" . }}
  labels:
    {{- include "groundschool.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "groundschool.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "groundschool.selectorLabels" . | nindent 8 }}
    spec:
      volumes:
        - name: web-data
          persistentVolumeClaim:
            claimName: web-nfs-pvc
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          envFrom:
            - configMapRef:
                name: {{ .Chart.Name }}-configmap
            - secretRef:
                name: {{ .Chart.Name }}-secrets
          livenessProbe:
            httpGet:
              path: /health
              port: http
          readinessProbe:
            httpGet:
              path: /health
              port: http
          volumeMounts:
            - mountPath: "/mnt"
              name: web-data
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
