apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: web-nfs-pvc
  labels:
    {{- include "groundschool.labels" . | nindent 4 }}
spec:
  storageClassName: nfs
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Gi

